### ISSUE TITLE
Mars DataFrame roadmap

### ISSUE THREAD

**Issue by hekaisheng** [mars-project/mars#495]
Mars now can create a DataFrame from pandas and support some experimental operations, in the next few months, most DataFrame operations will be supported.

## Element-wise Operations
- basic arithmetic
  - [x] add, radd (#177, #351, #506, #507, #582, #737 )
  - [x] subtract, rsub (#787)
  - [x] multiply, rmul (#980)
  - [x] divide, floordiv, truediv (#737)
  - [x] pow, rpow (#980)
  - [x] dot (#980)
- comparison
  - [x] lt, gt, le, ge, ne, eq (#921)
- math
  - [x] abs (#433, #432 )
  - [x] log, log2, log10 (#957)
  - [x] trignometric function (sin, cos, tan, etc.) (#957)
  - [x] radians, degrees (#957)
  - [x] ceil, round (#957)
  - [x] exp, expm1 (#957)

## Indexing
  - [x] indexing operation [] (#625, #682)
  - [x] attribute operation . (#625)
  - [x] iloc (#607, #638, #1016)
  - [x] loc (#1042)
  - [x] set_index (#638)
  - [x] reset_index (#915)
  - [x] isin (#1058, #1584)

## Statistic
- reduction
  - [x] sum (#575, #591)
  - [x] mean (#907)
  - [x] max, min (#789)
  - [x] count (#900)
  - [x] std, var (#977)
  - [x] nunique (#1137)
- cumlative
  - [x] cumsum, cumprod, cummax, cummin (#1019)

## Function application, GroupBy & window
  - [x] groupby (#568)
  - [x] apply (#1038)
  - [x] agg (#767, #1030)
  - [x] transform (#1084)
  - [x] rolling (#1045)

## Combining
  - [x] append (#1026)
  - [x] merge (#574)
  - [x] join (#571, #574)
  - [x] concat (#1040)

## Sorting
  - [x] sort_index (#1053)
  - [x] sort_values (#1046)

## Conversion

  - [x] from_tensor, to_dataframe (#524, #791)
  - [x] to_tensor, from_dataframe (#524, #791)

## Input/Output

 - [x] read_csv (#367, #807)
 - [x] read_parquet (#1576)
 - [x] read_sql (#986, #1297)
 - [x] to_csv (#966)
 - [x] to_parquet (#1652)
 - [x] to_sql (#1264)

## Others

  - [x] fillna (#1029)
  - [x] get_dummies (#570)

**Comment by qinxuye** [comment]
All tasks completed, hooray!
